$('#caro1').owlCarousel({
    loop:true,
    autoplay:true,
    margin:10,
    nav:false,
    dots:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:5
        }
    }
})
$('#caro2').owlCarousel({
    loop:true,
    autoplay:true,
    margin:10,
    nav:true,
    dots:true,
    responsive:{
        0:{
            items:1
        }
    }
})
$('#caro3').owlCarousel({
    loop:true,
    autoplay:true,
    margin:10,
    nav:true,
    dots:true,
    responsive:{
        0:{
            items:1
        }
    }
})
AOS.init();